apiVersion: v1
kind: List
items:

- kind: BuildConfig
  apiVersion: "v1"
  metadata:
    annotations:
      description: Generic ML/AI Jupyther notebook project
      template.alpha.openshift.io/wait-for-ready: 'true'
    name: 'notebook-ml'
  spec:
    
    runPolicy: "Serial" 
    
    triggers: 
      - type: "GitHub"
        github:
          secret: "notebook-ml"
      - type: "Generic"
        generic:
          secret: "notebook-ml"
      - type: "ImageChange"
    
    source: 
      git:
        uri: "https://github.com/stufff-ml/notebook-ml"
        ref: "master"
      contextDir: "assets"
    
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: Dockerfile
        forcePull: true
    
    output:
      to:
        kind: ImageStreamTag
        name: 'notebook-ml:latest'
    
- kind: ImageStream
  apiVersion: "v1"
  metadata:
    annotations:
      description: Generic ML/AI Jupyther notebook project
    name: 'notebook-ml'

metadata: []